"""add sch_email to ssce and bece

Revision ID: 090ff21adcf7
Revises: 95a893f37a72
Create Date: 2026-05-02 11:41:12.408699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090ff21adcf7'
down_revision: Union[str, Sequence[str], None] = '95a893f37a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece', sa.Column('sch_email', sa.String(), nullable=True))
    op.add_column('ssce', sa.Column('sch_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ssce', 'sch_email')
    op.drop_column('bece', 'sch_email')
    # ### end Alembic commands ###
