"""Add ssce and bece tables

Revision ID: 11b9de2a0d6d
Revises: a6991faf5b9c
Create Date: 2026-05-01 15:34:39.244552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b9de2a0d6d'
down_revision: Union[str, Sequence[str], None] = 'a6991faf5b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('sch_num', sa.String(), nullable=False),
    sa.Column('sch_name', sa.String(), nullable=False),
    sa.Column('cust_code', sa.String(), nullable=False),
    sa.Column('cust_name', sa.String(), nullable=False),
    sa.Column('cust_town', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('accd_year', sa.String(), nullable=True),
    sa.Column('lga', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bece_id'), 'bece', ['id'], unique=False)
    op.create_index(op.f('ix_bece_lga'), 'bece', ['lga'], unique=False)
    op.create_index(op.f('ix_bece_sch_num'), 'bece', ['sch_num'], unique=False)
    op.create_index(op.f('ix_bece_state_code'), 'bece', ['state_code'], unique=False)
    op.create_table('ssce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('sch_num', sa.String(), nullable=False),
    sa.Column('sch_name', sa.String(), nullable=False),
    sa.Column('cust_code', sa.String(), nullable=False),
    sa.Column('cust_name', sa.String(), nullable=False),
    sa.Column('cust_town', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('accd_year', sa.String(), nullable=True),
    sa.Column('lga', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssce_id'), 'ssce', ['id'], unique=False)
    op.create_index(op.f('ix_ssce_lga'), 'ssce', ['lga'], unique=False)
    op.create_index(op.f('ix_ssce_sch_num'), 'ssce', ['sch_num'], unique=False)
    op.create_index(op.f('ix_ssce_state_code'), 'ssce', ['state_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssce_state_code'), table_name='ssce')
    op.drop_index(op.f('ix_ssce_sch_num'), table_name='ssce')
    op.drop_index(op.f('ix_ssce_lga'), table_name='ssce')
    op.drop_index(op.f('ix_ssce_id'), table_name='ssce')
    op.drop_table('ssce')
    op.drop_index(op.f('ix_bece_state_code'), table_name='bece')
    op.drop_index(op.f('ix_bece_sch_num'), table_name='bece')
    op.drop_index(op.f('ix_bece_lga'), table_name='bece')
    op.drop_index(op.f('ix_bece_id'), table_name='bece')
    op.drop_table('bece')
    # ### end Alembic commands ###
