"""Add accreditation_type to SSCE and BECE

Revision ID: 23f9d0eadd75
Revises: 090ff21adcf7
Create Date: 2026-05-03 11:00:10.882234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f9d0eadd75'
down_revision: Union[str, Sequence[str], None] = '090ff21adcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece', sa.Column('accreditation_type', sa.String(), nullable=True))
    op.add_column('ssce', sa.Column('accreditation_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ssce', 'accreditation_type')
    op.drop_column('bece', 'accreditation_type')
    # ### end Alembic commands ###
