"""add lga table

Revision ID: 95a893f37a72
Revises: 11b9de2a0d6d
Create Date: 2026-05-01 20:00:29.739742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a893f37a72'
down_revision: Union[str, Sequence[str], None] = '11b9de2a0d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('lga_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lgas_id'), 'lgas', ['id'], unique=False)
    op.create_index(op.f('ix_lgas_lga_name'), 'lgas', ['lga_name'], unique=False)
    op.create_index(op.f('ix_lgas_state_code'), 'lgas', ['state_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lgas_state_code'), table_name='lgas')
    op.drop_index(op.f('ix_lgas_lga_name'), table_name='lgas')
    op.drop_index(op.f('ix_lgas_id'), table_name='lgas')
    op.drop_table('lgas')
    # ### end Alembic commands ###
