"""Add lga_code to LGAModel

Revision ID: c2a6eccce5f4
Revises: 23f9d0eadd75
Create Date: 2026-05-03 11:48:21.074135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a6eccce5f4'
down_revision: Union[str, Sequence[str], None] = '23f9d0eadd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lgas', sa.Column('lga_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_lgas_lga_code'), 'lgas', ['lga_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lgas_lga_code'), table_name='lgas')
    op.drop_column('lgas', 'lga_code')
    # ### end Alembic commands ###
