"""Add lga_code to SSCE and BECE tables

Revision ID: fcd24608ccff
Revises: c2a6eccce5f4
Create Date: 2026-05-03 12:05:43.747958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd24608ccff'
down_revision: Union[str, Sequence[str], None] = 'c2a6eccce5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bece', sa.Column('lga_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_bece_lga_code'), 'bece', ['lga_code'], unique=False)
    op.add_column('ssce', sa.Column('lga_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_ssce_lga_code'), 'ssce', ['lga_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssce_lga_code'), table_name='ssce')
    op.drop_column('ssce', 'lga_code')
    op.drop_index(op.f('ix_bece_lga_code'), table_name='bece')
    op.drop_column('bece', 'lga_code')
    # ### end Alembic commands ###
